### ISSUE TITLE
Gnuradio 3.9 specified in cmake

### ISSUE THREAD

**Issue by srsampson** [ast/gr-airspy#1]
Actually I'm still running 3.7, but I don't see a 3.9 release in the repository.

```
$ cmake -DENABLE_DOXYGEN=off ..
-- Build type not specified: defaulting to release.
CMake Error at CMakeLists.txt:88 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.9".
```

**Comment by ast** [comment]
Thank you for the feedback. I have been using the git HEAD version of GNURadio and apparently someone decided to bump the version in the build system to 3.9. 3.8 is still the latest release.

I just pushed 4802443e7ef0b5394622c657d547240749668b62. I have temporarily removed the GNURadio version requirement from the cmake file. Should build with 3.8 and maybe 3.7. Feel free to give it a try!

**Comment by srsampson** [comment]
I'll give it a try this afternoon and report back. I originally tried just changing the 3.9 to 3.7 but that didn't work, so I'll try your suggestion and comment out the line - thanks!

**Comment by ast** [comment]
Don't comment out the line. Just remove the version so it says:

```find_package(Gnuradio REQUIRED)```

Not sure about 3.7 but 3.8 should work.

**Comment by srsampson** [comment]
gnuradio 3.7 is a no-go, but I have successfully installed 3.8 and gr-airspy.

Thanks! ... and this issue can be closed.
